export const TYPE_DIR = "directory";
export const ACTIONSHEET_TITLE = "Optionen";
export const RENAME_OPTION = "Umbenennen";
export const MORE_INFORMATION_OPTION = "Mehr Informationen";
export const MOVE_OPTION = "Verschieben";
export const DELETE_OPTION = "Löschen";
export const DOWNLOAD_OPTION = "Download";
export const DRAWER_TITLE = "File-Browser-App";
export const LOGOUT_STRING = "Ausloggen";
